<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="0" name="documents.tests.clientpy.test_client_table" tests="5" time="0.129355192184"><testcase classname="documents.tests.clientpy.test_client_table.When_table_rows_and_columns_are_added" name="test_should_raise_exception_for_out_of_bounds_cell_label" time="0.00795412063599"></testcase><testcase classname="documents.tests.clientpy.test_client_table.When_table_rows_and_columns_are_added" name="test_row_count_and_column_count_are_correct" time="0.00786018371582"></testcase><testcase classname="documents.tests.clientpy.test_client_table.When_table_rows_and_columns_are_added" name="test_should_have_table_cell_values" time="0.00784993171692"></testcase><testcase classname="documents.tests.clientpy.test_client_table.When_table_rows_and_columns_are_added" name="test_rows_and_columns_are_in_the_right_order" time="0.00756502151489"></testcase><testcase classname="documents.tests.clientpy.test_client_table.When_table_cell_values_are_set" name="test_should_have_table_cell_values" time="0.0981259346008"></testcase></testsuite>
