<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="0" name="documents.tests.document_validation.test_validation_failed" tests="4" time="16.6723856926"><testcase classname="documents.tests.document_validation.test_validation_failed.MarkValidationJobAsFailedTestCase" name="test_fail_attempts_to_fetch_system_membership_with_None_passed_in" time="4.39071297646"></testcase><testcase classname="documents.tests.document_validation.test_validation_failed.MarkValidationJobAsFailedTestCase" name="test_set_failure_none_passed_in" time="4.11203289032"></testcase><testcase classname="documents.tests.document_validation.test_validation_failed.MarkValidationJobAsFailedTestCase" name="test_set_failure_successful" time="3.99876093864"></testcase><testcase classname="documents.tests.document_validation.test_validation_failed.MarkValidationJobAsFailedTestCase" name="test_set_failure_with_exception_object" time="4.17087888718"></testcase></testsuite>
